services:
  go_example_database:
    image: postgres:17-bookworm
    container_name: go_example_database
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "500M"
        max-file: "3"
    env_file: .env.postgres
    volumes:
      - ./docker-data/db/postgres-data:/var/lib/postgresql/data

  go_example_app:
    build: .
    container_name: go_example_app
    restart: always
    ports:
      - "3090:3090"
    depends_on:
      go_example_database:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "500M"
        max-file: "3"
    env_file: .env
